std = 'lua51'

quiet = 1 -- suppress report output for files without warnings

exclude_files = {
    '.luacheckrc'
}

ignore = {
	'11./SLASH_.*', -- Setting an undefined (Slash handler) global variable
	'11./BINDING_.*', -- Setting an undefined (Keybinding header) global variable
	'11./BTWLOADOUTS.*', -- Setting an undefined (Keybinding header) global variable
	'631', -- line is too long

    -- Remove later
	'211', -- unused local variable
	'212', -- unused argument
    '213', -- unused loop variable
	'231', -- local variable never accessed
	'232', -- argument never accessed
    '233', -- loop variable never accessed
    '311',
    '314',
    '4..', -- Redefining variables
    '542',
    '611',
    '612',
    '614',
}

globals = {
    -- BtWLoadouts Frames
    'BtWLoadoutsFrame',
    'BtWLoadoutsLogFrame',
    'BtWLoadoutsConditionsAffixesDropDownList',
    'BtWLoadoutsMinimapButton',
    'BtWLoadoutsImportFrame',

    -- BtWLoadouts Mixins
    'BtWLoadoutsActionBarsMixin',
    'BtWLoadoutsActionButtonMixin',
    'BtWLoadoutsAzeriteEssenceButtonMixin',
    'BtWLoadoutsAzeriteMilestoneSlotMixin',
    'BtWLoadoutsCharacterDropDownMixin',
    'BtWLoadoutsConditionsAffixesMixin',
    'BtWLoadoutsConditionsMixin',
    'BtWLoadoutsEquipmentMixin',
    'BtWLoadoutsEssencesMixin',
    'BtWLoadoutsFrameMixin',
    'BtWLoadoutsIgnoreActionBarMixin',
    'BtWLoadoutsImportFrameMixin',
    'BtWLoadoutsImportMixin',
    'BtWLoadoutsItemSlotButtonMixin',
    'BtWLoadoutsLoadoutsMixin',
    'BtWLoadoutsLogFrameMixin',
    'BtWLoadoutsMinimapMixin',
    'BtWLoadoutsPvPTalentsMixin',
    'BtWLoadoutsRestrictionsDropDownMixin',
    'BtWLoadoutsSetDropDownMixin',
    'BtWLoadoutsSetsScrollListItemMixin',
    'BtWLoadoutsSidebarMixin',
    'BtWLoadoutsSoulbindDropDownMixin',
    'BtWLoadoutsSoulbindNodeMixin',
    'BtWLoadoutsSoulbindsMixin',
    'BtWLoadoutsSoulbindTreeNodeLinkMixin',
    'BtWLoadoutsSpecDropDownMixin',
    'BtWLoadoutsTalentButtonMixin',
    'BtWLoadoutsTalentSelectionMixin',
    'BtWLoadoutsTalentsMixin',

    -- BtWLoadouts Functions
    'BtWLoadoutsTabFrame_OnLoad',
    'BtWLoadoutsTabFrame_SetEnabled',
    'BtWLoadoutsTabFrame_ReanchorTabs',
    'BtWLoadoutsMinimapMenu_Init',

    -- BtWLoadouts Saved Variables
    'BtWLoadoutsHelpTipFlags',
    'BtWLoadoutsSets',
    'BtWLoadoutsCollapsed',
    'BtWLoadoutsCategories',
    'BtWLoadoutsFilters',
    'BtWLoadoutsSpecInfo',
    'BtWLoadoutsEssenceInfo',
    'BtWLoadoutsRoleInfo',
    'BtWLoadoutsCharacterInfo',
    'BtWLoadoutsSettings',

    -- FrameXML Misc
    'StaticPopupDialogs',
    'UISpecialFrames',
    'SlashCmdList',
}
new_read_globals = {
    -- Addon Globals
    'OneRingLib',
    'LibStub',
    'ElvUI',
    'GetMinimapShape',

    --
    'Enum',

    -- Deprecated API Functions
    'IsQuestFlaggedCompleted',

    -- API Functions
    'bit.band',
    'bit.bor',
    'bit.bxor',
    'bit.lshift',
    'bit.rshift',
    'GetPvpTalentLink',
    'LearnPvpTalent',
    'C_SpecializationInfo.GetPvpTalentUnlockLevel',
    'C_AzeriteEmpoweredItem.GetAllTierInfo',
    'C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItem',
    'C_AzeriteEmpoweredItem.IsPowerSelected',
    'C_AzeriteEssence.ActivateEssence',
    'C_AzeriteEssence.GetEssenceHyperlink',
    'C_AzeriteEssence.GetEssenceInfo',
    'C_AzeriteEssence.GetEssences',
    'C_AzeriteEssence.GetMilestoneEssence',
    'C_AzeriteEssence.GetMilestoneInfo',
    'C_AzeriteEssence.UnlockMilestone',
    'C_ChallengeMode.GetAffixInfo',
    'C_ClassColor.GetClassColor',
    'C_Covenants.GetActiveCovenantID',
    'C_Covenants.GetCovenantData',
    'C_Covenants.GetCovenantIDs',
    'C_CreatureInfo.GetClassInfo',
    'C_CreatureInfo.GetFactionInfo',
    'C_CreatureInfo.GetRaceInfo',
    'C_EncounterJournal.IsEncounterComplete',
    'C_EquipmentSet.GetEquipmentSetID',
    'C_EquipmentSet.GetEquipmentSetIDs',
    'C_EquipmentSet.GetEquipmentSetInfo',
    'C_EquipmentSet.GetIgnoredSlots',
    'C_EquipmentSet.GetItemIDs',
    'C_EquipmentSet.GetItemLocations',
    'C_EquipmentSet.ModifyEquipmentSet',
    'C_EquipmentSet.PickupEquipmentSet',
    'C_EquipmentSet.SaveEquipmentSet',
    'C_Item.GetItemLink',
    'C_Map.GetAreaInfo',
    'C_Map.GetBestMapForUnit',
    'C_MountJournal.GetDisplayedMountInfo',
    'C_MountJournal.GetMountInfoByID',
    'C_MountJournal.GetNumDisplayedMounts',
    'C_MountJournal.Pickup',
    'C_MythicPlus.GetCurrentAffixes',
    'C_PetJournal.GetPetInfoByPetID',
    'C_PetJournal.PickupPet',
    'C_QuestLog.IsQuestFlaggedCompleted',
    'C_Soulbinds.ActivateSoulbind',
    'C_Soulbinds.GetActiveSoulbindID',
    'C_Soulbinds.GetNode',
    'C_Soulbinds.GetSoulbindData',
    'C_Soulbinds.SelectNode',
    'C_SpecializationInfo.GetAllSelectedPvpTalentIDs',
    'C_SpecializationInfo.GetPvpTalentSlotInfo',
    'C_Timer.After',
    'ClearCursor',
    'CreateFrame',
    'CreateMacro',
    'CursorHasItem',
    'EditMacro',
    'EJ_GetEncounterInfo',
    'FindBaseSpellByID',
    'format',
    'GetActionInfo',
    'GetActionText',
    'GetActionTexture',
    'GetAddOnInfo',
    'GetAddOnMetadata',
    'GetBuildInfo',
    'GetClassInfo',
    'GetContainerFreeSlots',
    'GetContainerItemInfo',
    'GetContainerItemInfo',
    'GetContainerItemLink',
    'GetContainerNumFreeSlots',
    'GetContainerNumSlots',
    'GetCursorInfo',
    'GetCursorPosition',
    'GetDifficultyInfo',
    'GetExpansionLevel',
    'GetFlyoutInfo',
    'GetInstanceInfo',
    'GetInventoryItemID',
    'GetInventoryItemLink',
    'GetInventorySlotInfo',
    'GetItemCount',
    'GetItemFamily',
    'GetItemGem',
    'GetItemInfo',
    'GetItemInfoInstant',
    'GetItemQualityColor',
    'GetItemUniqueness',
    'GetLocale',
    'GetMacroBody',
    'GetMacroIndexByName',
    'GetMacroInfo',
    'GetNumClasses',
    'GetNumMacros',
    'GetNumSpecializations',
    'GetNumSpecializationsForClassID',
    'GetNumSpellTabs',
    'GetPlayerAuraBySpellID',
    'GetPvpTalentInfoByID',
    'GetRealmName',
    'GetRealZoneText',
    'GetSpecialization',
    'GetSpecializationInfo',
    'GetSpecializationInfoByID',
    'GetSpecializationInfoForClassID',
    'GetSpecializationRole',
    'GetSpecializationRoleByID',
    'GetSpellBookItemInfo',
    'GetSpellInfo',
    'GetSpellTabInfo',
    'GetSubZoneText',
    'GetTalentInfo',
    'GetTalentInfoByID',
    'GetTalentInfoBySpecialization',
    'GetTalentLink',
    'GetTalentTierInfo',
    'GetTime',
    'GetVoidItemHyperlinkString',
    'GetVoidItemInfo',
    'hooksecurefunc',
    'InCombatLockdown',
    'IsEncounterInProgress',
    'IsEquippableItem',
    'IsInventoryItemLocked',
    'IsModifiedClick',
    'IsPlayerMoving',
    'IsResting',
    'IsSpellKnown',
    'LearnTalent',
    'min',
    'MouseIsOver',
    'PickupAction',
    'PickupContainerItem',
    'PickupInventoryItem',
    'PickupItem',
    'PickupMacro',
    'PickupPetSpell',
    'PickupPvpTalent',
    'PickupSpell',
    'PickupSpellBookItem',
    'PlaceAction',
    'PlaySound',
    'SetCursor',
    'SetSpecialization',
    'sort',
    'strlower',
    'strsplit',
    'strtrim',
    'table.wipe',
    'tinsert',
    'UnitAura',
    'UnitCastingInfo',
    'UnitClass',
    'UnitFullName',
    'UnitGUID',
    'UnitIsDead',
    'UnitLevel',
    'UnitName',
    'UnitOnTaxi',
    'UnitRace',
    'UnitSex',
    'wipe',

    -- Global Strings
    'ARENA',
    'BAG_FILTER_EQUIPMENT',
    'BATTLEGROUNDS',
    'CONTINUE',
    'COVENANT_PREVIEW_SOULBINDS',
    'DELETE',
    'DUNGEONS',
    'DURABILITY_TEMPLATE',
    'EQUIPMENT_SETS',
    'ERR_ITEM_UNIQUE_EQUIPPABLE',
    'ERR_LEARN_ABILITY_S',
    'ERR_LEARN_PASSIVE_S',
    'ERR_LEARN_SPELL_S',
    'ERR_SPELL_UNLEARNED_S',
    'ITEM_ARTIFACT_VIEWABLE',
    'ITEM_AZERITE_EMPOWERED_VIEWABLE',
    'ITEM_AZERITE_ESSENCES_VIEWABLE',
    'ITEM_CREATED_BY',
    'ITEM_SET_BONUS',
    'ITEM_SOCKETABLE',
    'ITEM_UNSELLABLE',
    'NAME',
    'NEW',
    'NO',
    'NONE',
    'OTHER',
    'PAPERDOLL_NEWEQUIPMENTSET',
    'PVP_TALENTS',
    'RAIDS',
    'SCENARIOS',
    'SELL_PRICE',
    'SPECIALIZATION',
    'TALENT_SPEC_ACTIVATE',
    'TALENTS',
    'UPDATE',
    'VIDEO_OPTIONS_ENABLED',
    'WORLD',
    'YES',

	-- FrameXML Functions
    'C_AzeriteEssence.GetMilestoneSpell',
    'CloseDropDownMenus',
    'CopyTable',
    'CreateFramePool',
    'CreateTexturePool',
    'EquipmentManager_UnpackLocation',
    'FindSpellOverrideByID',
    'FramePool_HideAndClearAnchors',
    'GameTooltip_Hide',
    'GetInventoryItemsForSlot',
    'GetSpellCooldown',
    'HybridScrollFrame_CreateButtons',
    'HybridScrollFrame_GetOffset',
    'HybridScrollFrame_Update',
    'ItemLocation.CreateEmpty',
    'ItemLocation.CreateFromBagAndSlot',
    'ItemLocation.CreateFromEquipmentSlot',
    'MacroFrame_Update',
    'Mixin',
    'PanelTemplates_GetSelectedTab',
    'PanelTemplates_SetNumTabs',
    'PanelTemplates_SetTab',
    'PanelTemplates_UpdateTabs',
    'RegisterStateDriver',
    'SetItemButtonQuality',
    'SetItemButtonTexture',
    'SharedTooltip_SetBackdropStyle',
    'StaticPopup_Hide',
    'StaticPopup_Show',
    'StaticPopup_Visible',
    'tCompare',
    'ToggleDropDownMenu',
    'UIDropDownMenu_AddButton',
    'UIDropDownMenu_AddSeparator',
    'UIDropDownMenu_CreateInfo',
    'UIDropDownMenu_DisableDropDown',
    'UIDropDownMenu_EnableDropDown',
    'UIDropDownMenu_Initialize',
    'UIDropDownMenu_JustifyText',
    'UIDropDownMenu_SetSelectedValue',
    'UIDropDownMenu_SetText',
    'UIDropDownMenu_SetWidth',
    'UIErrorsFrame',
    'ChatFrame_AddMessageEventFilter',
    'ChatFrame_RemoveMessageEventFilter',
    'RegionUtil.CalculateAngleBetween',
    'BackdropTemplateMixin.OnBackdropLoaded',
    'GetFactionColor',

    -- FrameXML Frames
    'BankFrame',
    'GameTooltip',
    'ItemRefTooltip',
    'MacroFrame',
    'UIErrorsFrame',
    'UIParent',
    'Minimap',
    'IconIntroTracker',

    -- FrameXML Constants
    'BACKPACK_CONTAINER',
    'BANK_CONTAINER',
    'GAME_TOOLTIP_BACKDROP_STYLE_AZERITE_ITEM',
    'INVSLOT_BODY',
    'INVSLOT_FIRST_EQUIPPED',
    'INVSLOT_LAST_EQUIPPED',
    'INVSLOT_NECK',
    'INVSLOT_TABARD',
    'ITEM_INVENTORY_BAG_BIT_OFFSET',
    'ITEM_INVENTORY_BANK_BAG_OFFSET',
    'ITEM_INVENTORY_LOCATION_BAG',
    'ITEM_INVENTORY_LOCATION_BAGS',
    'ITEM_INVENTORY_LOCATION_BANK',
    'ITEM_INVENTORY_LOCATION_PLAYER',
    'LOCALIZED_CLASS_NAMES_MALE',
    'MAX_ACCOUNT_MACROS',
    'MAX_CHARACTER_MACROS',
    'MAX_TALENT_TIERS',
    'NORMAL_FONT_COLOR',
    'NUM_BAG_SLOTS',
    'NUM_BANKBAGSLOTS',
    'STATICPOPUP_NUMDIALOGS',
    'SOUNDKIT',
}