-- Russian translations. Thanks to Void_OW and Hubbotu on Curse

if GetLocale() ~= "ruRU" then return; end

local _, Internal = ...
local L = Internal.L

L["A tome is needed to continue equiping your set."] = "Для применения этого набора необходим фолиант."
L["Action Bars"] = "Панели команд"
L["Activate"] = "Применить"
L["Activate profile %s?"] = "Применить профиль %s?"
L[ [=[Activate spec %s?
This set will require a tome or rested to activate]=] ] = "Применить специализацию %s? Этот набор потребует фолианта или зоны отдыха для применения"
L[ [=[Activate spec %s?
This will use a Tome]=] ] = "Применить специализацию %s? Это задействует Фолиант"
L[ [=[Activate the following profile?
]=] ] = "Применить этот профиль?"
L["Activate your profile."] = "Задействуйте ваш профиль."
L["Activating Loadout"] = "Применяется Набор"
L["Any"] = "Любой"
L["Are you sure you wish to delete the set \"%s\", this set is in use by one or more profiles. This cannot be reversed."] = "Вы уверены что хотите удалить набор \"%s\"? Этот набор используется в одном или нескольких профилях. Это действие невозможно отменить."
L["Are you sure you wish to delete the set \"%s\". This cannot be reversed."] = "Вы уверены что хотите удалить набор \"%s\"? Это действие нельзя отменить."
L["Arena"] = "Арена"
L["Battle for Azeroth"] = "Battle for Azeroth"
L["Battlegrounds"] = "Поле Боя"
L["BtWLoadouts"] = "Аддон BtWLoadouts"
L["Can not edit equipment manager sets."] = "Изменять наборы экипировки нельзя."
L["Can not equip sets for other characters."] = "Применить наборы для других персонажей нельзя."
L["Cannot create any more macros"] = "Невозможно создать больше макросов."
L["Cannot create macros while in combat"] = "Невозможно создать макрос в бою"
L["Cata"] = "Катаклизм"
L["Change the name of your new profile."] = "Измените имя вашего нового профиля."
L["Changing to %s..."] = "Заменить на %s..."
L["Changing..."] = "Заменить..."
L["Classic"] = "Классика"
L[ [=[Click to open BtWLoadouts.
Right Click to enable and disable settings.]=] ] = "Нажмите для запуска BtWLoadouts. Правая кнопка мыши открывает настройки."
L["Conditions"] = "Условия"
L["Could not find a valid set"] = "Нет подходящего набора"
L["Create a talent set for your new profile."] = "Создайте набор талантов для вашего нового профиля."
L["Delete"] = "Удалить"
L["Dungeons"] = "Подземелья"
L["Enabled"] = "Включено"
L["Equipment"] = "Экипировка"
L["Essences"] = "Сущности"
L["Failed to change equipment set"] = "Не удалось изменить комплект экипировки"
L["Legion"] = "Легион"
L["Name"] = "Название"
L["New"] = "Новый"
L["New %s Equipment Set"] = "Новый набор экипировки %s"
L["New %s Set"] = "Новый набор %s"
L["New Condition Set"] = "Новый набор условий"
L["New Profile"] = "Новый профиль"
L["New Set"] = "Новый Комплект"
L["None"] = "Нет"
L["Other"] = "Другое"
L["Panda"] = "Пандария"
L["Profile"] = "Профиль"
L["Profiles"] = "Профили"
L["PvP Talents"] = "PvP Таланты"
L["Raids"] = "Рейды"
L["Scenarios"] = "Сценарии"
L["Settings"] = "Настройки"
L["Shift+Left Mouse Button to ignore a slot."] = "Shift+Левая кнопка мыши игнорирует слот."
L["Show minimap icon"] = "Показывать кнопку на мини-карте"
L["Specialization"] = "Специализация"
L["Talents"] = "Таланты"
L["TBC"] = "TBC"
L["To begin, create a new set."] = "Для начала, создайте новый набор."
L["Toggle BtWLoadouts"] = "Включить/выключить BtWLoadouts"
L["Unnamed"] = "Неназванный"
L["Waiting for combat to end"] = "Идет ожидание окончания боя"
L["Waiting for essence cooldown"] = "Идет ожидание перезарядки эссенции"
L["Waiting for specialization change"] = "Идет ожидание смены специализации"
L["Waiting for talent cooldown"] = "Идет ожидание перезарядки таланта"
L["Waiting to change specialization"] = "Идет ожидание смены специализации"
L["WoD"] = "Дренор"
L["World"] = "Мир"
L["Wrath"] = "WotLK"
