-- Traditional Chinese translations. Thanks to BNS333 and RainbowUI on Curse

if GetLocale() ~= "zhTW" then return; end

local _, Internal = ...
local L = Internal.L

L["A tome is needed to continue equiping your set."] = "要繼續裝備您的設定一個靜心之卷是需要的。"
L["Action Bars"] = "動作列"
L["Activate"] = "啟用"
L["Activate profile %s?"] = "啟動設定檔 %s？"
L[ [=[Activate spec %s?
This set will require a tome or rested to activate]=] ] = "啟動專精 %s？\n此設定需要靜心之卷或休息區域來啟動"
L[ [=[Activate spec %s?
This will use a Tome]=] ] = "啟動專精 %s？\n這會用掉一個靜心之卷"
L[ [=[Activate the following profile?
]=] ] = "啟動以下的設定檔？"
L["Activate your profile."] = "啟動您的設定檔。"
L["Activating Loadout"] = "裝載啟用中"
L["Any"] = "任何"
L["Are you sure you wish to delete the set \"%s\", this set is in use by one or more profiles. This cannot be reversed."] = "您確定想要刪除設定\"%s\"。此設定由一個或多個設定檔使用中。這是無法回復的。"
L["Are you sure you wish to delete the set \"%s\". This cannot be reversed."] = "您確定想要刪除設定\"%s\"。這是無法回復的。"
L["Arena"] = "競技場"
L["Battle For Azeroth"] = "決戰艾澤拉斯"
L["Battlegrounds"] = "戰場"
L["BtWLoadouts"] = "BtWLoadouts"
L["Can not edit equipment manager sets."] = "無法編輯換裝管理套裝。"
L["Can not equip sets for other characters."] = "無法裝備其他角色的套裝。"
L["Cannot create any more macros"] = "無法建立任何更多的巨集"
L["Cannot create macros while in combat"] = "在戰鬥中無法建立巨集"
L["Click to open BtWLoadouts.\nRight Click to enable and disable settings."] = "點擊來開啟BtWLoadouts。\n右鍵點擊來啟用與停用設定。"
L["Could not find a valid set"] = "無法找到有效設定"
L["Cata"] = "浩劫與重生"
L["Change the name of your new profile."] = "變更您新設定檔的名稱。"
L["Changing to %s..."] = "變更為%s..."
L["Changing..."] = "變更中..."
L["Classic"] = "經典版"
L["Conditions"] = "環境"
L["Create a talent set for your new profile."] = "為您的新設定檔建立一套天賦設定。"
L["Delete"] = "刪除"
L["Dungeons"] = "地城"
L["Enabled"] = "啟用"
L["Equipment"] = "裝備"
L["Essences"] = "精華"
L["Failed to change equipment set"] = "變更裝備套裝失敗"
L["Legion"] = "軍臨天下"
L["Name"] = "名稱"
L["New"] = "新"
L["New %s Equipment Set"] = "新%s裝備設定"
L["New %s Set"] = "新%s設定"
L["New Condition Set"] = "新環境設定"
L["New Profile"] = "新設定檔"
L["New Set"] = "新套裝"
L["None"] = "無"
L["Other"] = "其他"
L["Panda"] = "潘達利亞之謎"
L["Profile"] = "設定檔"
L["Profiles"] = "設定檔"
L["PvP Talents"] = "PvP天賦"
L["Raids"] = "團隊"
L["Scenarios"] = "事件"
L["Settings"] = "設置"
L["Shift+Left Mouse Button to ignore a slot."] = "Shift+ 滑鼠左鍵來忽略一個部位。"
L["Show minimap icon"] = "顯示小地圖按鈕"
L["Specialization"] = "專精"
L["Talents"] = "天賦"
L["TBC"] = "燃燒的遠征"
L["To begin, create a new set."] = "要開始前，建立一個新設定。"
L["Toggle BtWLoadouts"] = "切換BtWLoadouts"
L["Unnamed"] = "未命名"
L["Waiting for combat to end"] = "等候戰鬥結束"
L["Waiting for essence cooldown"] = "等候精華冷卻"
L["Waiting for specialization change"] = "等候專精切換"
L["Waiting for talent cooldown"] = "等候天賦冷卻"
L["Waiting to change specialization"] = "等候變更專精"
L["WoD"] = "德拉諾之霸"
L["World"] = "世界"
L["Wrath"] = "巫妖王之怒"
