-- Traditional Chinese translations. Thanks to BNS333 on Curse

if GetLocale() ~= "zhTW" then return; end

local _, Internal = ...
local L = Internal.L

L["Profile"] = "設定檔"
L["Profiles"] = "設定檔"
L["Essences"] = "精華"
L["Conditions"] = "環境"
L["Classic"] = "經典版"
L["TBC"] = "燃燒的遠征"
L["Wrath"] = "巫妖王之怒"
L["Cata"] = "浩劫與重生"
L["Panda"] = "潘達利亞之謎"
L["WoD"] = "德拉諾之霸"
L["Legion"] = "軍臨天下"
L["Battle For Azeroth"] = "決戰艾澤拉斯"
L["Show minimap icon"] = "顯示小地圖按鈕"
L["Activate profile %s?"] = "啟動設定檔 %s？"
L["Activate the following profile?\n"] = "啟動以下的設定檔？\n"
L["Activate spec %s?\nThis set will require a tome or rested to activate"] = "啟動專精 %s？\n此設定需要靜心之卷或休息區域來啟動"
L["Activate spec %s?\nThis will use a Tome"] = "啟動專精 %s？\n這會用掉一個靜心之卷"
L["A tome is needed to continue equiping your set."] = "要繼續裝備您的設定一個靜心之卷是需要的。"
L["Are you sure you wish to delete the set \"%s\". This cannot be reversed."] = "您確定想要刪除設定\"%s\"。這是無法回復的。"
L["Are you sure you wish to delete the set \"%s\", this set is in use by one or more profiles. This cannot be reversed."] = "您確定想要刪除設定\"%s\"。此設定由一個或多個設定檔使用中。這是無法回復的。"
L["Any"] = "任何"
L["To begin, create a new set."] = "要開始前，建立一個新設定。"
L["Can not equip sets for other characters."] = "無法從其他角色裝備設定。"
L["Can not edit equipment manager sets."] = "無法編輯換裝管理設定。"
L["Shift+Left Mouse Button to ignore a slot."] = "Shift+ 滑鼠左鍵來忽略一個部位。"
L["Cannot create any more macros"] = "無法建立任何更多的巨集"
L["Cannot create macros while in combat"] = "在戰鬥中無法建立巨集"
L["Click to open BtWLoadouts.\nRight Click to enable and disable settings."] = "點擊來開啟BtWLoadouts。\n右鍵點擊來啟用與停用設定。"
L["Could not find a valid set"] = "無法找到有效設定"
L["New Profile"] = "新設定檔"
L["Change the name of your new profile."] = "改變您新設定檔的名稱。"
L["Create a talent set for your new profile."] = "為您的新設定檔建立一套天賦設定。"
L["Activate your profile."] = "啟動您的設定檔。"
L["New %s Set"] = "新%s設定"
L["New %s Equipment Set"] = "新%s裝備設定"
L["Other"] = "其他"
L["New Condition Set"] = "新環境設定"